### ISSUE TITLE
DecodeOgg

### ISSUE THREAD

**Issue by JAlHund** [defold/awesome-defold#10]
Optionally also attach two images DecodeOgg-hero.[png|jpg] (max 2400x666) and DecodeOgg-thumb.[png|jpg] (max 580x380).
{
    "name": "DecodeOgg",
    "description": "Native extension for decoding ogg files in wav.",
    "license": "MIT",
    "author": "Denis Makhortov",
    "library_url": "https://github.com/JAlHund/decodeogg",
    "project_url": "https://github.com/JAlHund/decodeogg",
    "forum_url": "https://forum.defold.com/t/decodeogg-native-extension/64048",
    "website_url": "",
    "platforms": [
        "android",
        "windows"
    ],
    "tags": [
        "audio"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thanks! Added it: https://github.com/defold/awesome-defold/blob/master/assets/decodeogg.json

It should show up in the Asset Portal soon.
