### ISSUE TITLE
DefArc - Defold + Arcweave module for branching narrative

### ISSUE THREAD

**Issue by paweljarosz** [defold/awesome-defold#101]
Optionally also attach two images DefArc - Defold   Arcweave-hero.[png|jpg] (max 2400x666) and DefArc - Defold   Arcweave-thumb.[png|jpg] (max 580x380).
{
    "name": "DefArc - Defold   Arcweave",
    "description": "DefArc is an Arcweave runtime for Defold, a toolset to easily create branching, interactive narratives in your games!",
    "license": "MIT",
    "author": "Paweł Jarosz",
    "library_url": "https://github.com/paweljarosz/defarc/master.zip",
    "project_url": "https://github.com/paweljarosz/defarc",
    "forum_url": "https://forum.defold.com/t/defarc-defold-arcweave-tool-for-branching-conversations-and-narrative/70832",
    "website_url": "https://github.com/paweljarosz/defarc",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "game mechanic",
        "template projects",
        "tools",
        "tutorials",
        "util"
    ],
    "images": {
        "hero": "https://user-images.githubusercontent.com/11634203/166456687-a758d677-20c0-4a6c-99c9-867f6228085c.png",
        "thumb": "https://user-images.githubusercontent.com/11634203/166456744-d7f220ad-8327-4c63-be92-2104da4054d1.png"
    }
![Arcweave-hero](https://user-images.githubusercontent.com/11634203/166456687-a758d677-20c0-4a6c-99c9-867f6228085c.png)
![Arcweave-thumb](https://user-images.githubusercontent.com/11634203/166456744-d7f220ad-8327-4c63-be92-2104da4054d1.png)
}

**Comment by britzl** [comment]
https://github.com/defold/awesome-defold/blob/master/assets/defarc.json
