### ISSUE TITLE
Operator

### ISSUE THREAD

**Issue by astrochili** [defold/awesome-defold#102]
Optionally also attach two images Operator-hero.[png|jpg] (max 2400x666) and Operator-thumb.[png|jpg] (max 580x380).
{
    "name": "Operator",
    "description": "Camera movement controller for 3D games. Tweakable, smooth and cinematic.",
    "license": "MIT",
    "author": "Roman Silin",
    "library_url": "https://github.com/astrochili/defold-operator/archive/master.zip",
    "project_url": "https://github.com/astrochili/defold-operator/",
    "forum_url": "https://forum.defold.com/t/operator-camera-movement-controller-for-3d-games/71094",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "camera",
        "input",
        "animation"
    ],
    "images": {
        "hero": "https://user-images.githubusercontent.com/4752473/173253202-6da92bfa-e995-42db-b8e6-4ba64dbb624c.jpg",
        "thumb": "https://user-images.githubusercontent.com/4752473/173253203-5a890979-28e1-4b71-b50e-d68717dd9275.png"
    }
}

**Comment by britzl** [comment]
Added: https://github.com/defold/awesome-defold/commit/e727c594dfba46f047e19e358d02aa1e7f020ecb

**Comment by astrochili** [comment]
@britzl I think I may have done something wrong with this request, so here are the pictures:

![operator-thumb](https://user-images.githubusercontent.com/4752473/175777749-6c8d2dc9-8ace-4643-bf7c-38121b4148b4.png)
![operator-hero](https://user-images.githubusercontent.com/4752473/175777750-a5e4a61e-fbc7-4726-bfd5-1e63443c515c.jpeg)

**Comment by britzl** [comment]
Ah, no, I created the metadata in the wrong location
