### ISSUE TITLE
Galaxy Keeper: Space Shooter

### ISSUE THREAD

**Issue by Dr-Klaus** [defold/awesome-defold#106]
```json
{
    "name": "Galaxy Keeper: Space Shooter",
"description": "Shoot'em up! Alien attack! Defeat waves of invaders in hundreds missions! Fast-paced top-down shooter game.",
    "url": "https://www.bigbutton.co/galaxy-keeper-space-shooter",
    "developer": "BigButton Co Sp.z o.o.",
    "publisher": "BigButton Co Sp.z o.o.",
    "releasedate": "July 2022",
    "platforms": "iOS,Android,HTML5",
    "images": {
        "full": "https://user-images.githubusercontent.com/87762110/184133638-e94d02d7-8bb4-46cc-b469-967ad9129243.jpg",
        "half": "https://user-images.githubusercontent.com/87762110/184133628-57841d1f-cf7b-4d02-8402-62c0f2720e04.jpg",
        "third": "https://user-images.githubusercontent.com/87762110/184133618-e60e454a-b148-4113-aa40-59756762135d.jpg"
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page
![800x600](https://user-images.githubusercontent.com/87762110/184133618-e60e454a-b148-4113-aa40-59756762135d.jpg)
![1200x600](https://user-images.githubusercontent.com/87762110/184133628-57841d1f-cf7b-4d02-8402-62c0f2720e04.jpg)
![3000x750](https://user-images.githubusercontent.com/87762110/184133638-e94d02d7-8bb4-46cc-b469-967ad9129243.jpg)

**Comment by britzl** [comment]
Thank you! Great game!
