### ISSUE TITLE
Wortal

### ISSUE THREAD

**Issue by trdillon** [defold/awesome-defold#112]
Optionally also attach two images Wortal-hero.[png|jpg] (max 2400x666) and Wortal-thumb.[png|jpg] (max 580x380).
{
    "name": "Wortal",
    "description": "Wortal SDK native extension for Defold.",
    "license": "MIT",
    "author": "Digital Will Inc.",
    "library_url": "https://github.com/Digital-Will-Inc/wortal-sdk-defold/archive/master.zip",
    "project_url": "https://html5gameportal.com/",
    "forum_url": "",
    "website_url": "https://sdk.html5gameportal.com/wortal-defold/",
    "platforms": [
        "html5"
    ],
    "tags": [
        "ads",
        "analytics",
        "monetization",
        "platform"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}
![Wortal-SDK-Defold-hero](https://user-images.githubusercontent.com/26350151/193747220-be295240-63db-49fe-a32b-72c6f6aac6ec.png)
![Wortal-SDK-Defold-thumbnail](https://user-images.githubusercontent.com/26350151/193747243-f84e5b34-c998-4b25-bbe8-06e425265607.png)

**Comment by britzl** [comment]
Thanks. Added.
