### ISSUE TITLE
Defold Parser | Node module

### ISSUE THREAD

**Issue by Insality** [defold/awesome-defold#114]
![image](https://user-images.githubusercontent.com/3294627/196785276-3de6b50f-7c58-4608-94f6-cafe6b9cf9c8.png)

Optionally also attach two images Defold Parser-hero.[png|jpg] (max 2400x666) and Defold Parser-thumb.[png|jpg] (max 580x380).
{
    "name": "Defold Parser",
    "description": "Parse Defold files to JSON and back",
    "license": "MIT",
    "author": "Insality",
    "library_url": "",
    "project_url": "https://github.com/Insality/defold-parser",
    "forum_url": "https://forum.defold.com/t/defold-parser-node-module/71903",
    "website_url": "https://github.com/Insality/defold-parser",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "system",
        "util"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Added in commit https://github.com/defold/awesome-defold/commit/e1f4df466a9cc08ef2f78c2c5ffc7b82e494b867
