### ISSUE TITLE
No thumbnail or hero for m

### ISSUE THREAD

**Issue by wistpotion** [defold/awesome-defold#117]
I didn't know exactly how to send along the images (they aren't showing up in the assets section), hence the links (adding how to do that would help). I did notice that the links actually points the image in the repository, instead of the images themselves. So here are the proper links:
hero: `https://raw.githubusercontent.com/wistpotion/m/main/hero.png`
thumbnail: `https://raw.githubusercontent.com/wistpotion/m/main/thumbnail.png`

**Comment by britzl** [comment]
The preferred way si actually that we add the images to this repo instead of linking to an external source. I did that and it should be updated on the website in a couple of minutes:

https://github.com/defold/awesome-defold/commit/82d5a2f44a8d829e602549c6ac0a1a6dcf5e3600

**Comment by wistpotion** [comment]
Got it. Thanks!
