### ISSUE TITLE
Defold Typewriter

### ISSUE THREAD

**Issue by klaytonkowalski** [defold/awesome-defold#118]
Optionally also attach two images Defold Typewriter-hero.[png|jpg] (max 2400x666) and Defold Typewriter-thumb.[png|jpg] (max 580x380).
{
    "name": "Defold Typewriter",
    "description": "Defold Typewriter provides text scrolling and styling in a Defold game engine project.",
    "license": "MIT",
    "author": "Klayton Kowalski",
    "library_url": "https://github.com/klaytonkowalski/library-defold-typewriter/archives/main.zip",
    "project_url": "https://github.com/klaytonkowalski/library-defold-typewriter",
    "forum_url": "https://forum.defold.com/t/defold-typewriter/72078",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "gui"
    ],
    "images": {
        "hero": "defold-typewriter.png",
        "thumb": "defold-typewriter.png"
    }
}
![defold-typewriter](https://user-images.githubusercontent.com/70988652/202495564-8d9b1d2d-6e20-495f-9b35-5b1adf74a8db.png)

**Comment by klaytonkowalski** [comment]
> Thanks! Can you please attach the image(s) as well? Or is it ok to use a blank/default image?

Hi britzl, I'm not sure how to properly attach an image without forking the repo (I was brought here by the Asset Portal's submit button), so I just drag and dropped the thumbnail image to the bottom of the commit. If I need to fork instead, please let me know. Thanks.

**Comment by britzl** [comment]
> I just drag and dropped the thumbnail image

That's perfect!
