### ISSUE TITLE
editor-script-monarch

### ISSUE THREAD

**Issue by Jerakin** [defold/awesome-defold#12]
![editor-script-monarch-hero](https://user-images.githubusercontent.com/5273682/72210767-d6c7b980-34c0-11ea-9aa5-19aee5469f27.png)
![editor-script-monarch-thumb](https://user-images.githubusercontent.com/5273682/72210788-070f5800-34c1-11ea-839e-4ac27b8907aa.png)

{
    "name": "editor-script-monarch",
    "description": "This script adds a menu option to the context menu on a gui scene. When used it creates a collection and a gui_script and do a basic setup on them.",
    "license": "MIT License",
    "author": "Jerakin",
    "library_url": "https://github.com/Jerakin/editor-script-monarch/archive/master.zip",
    "project_url": "https://github.com/Jerakin/editor-script-monarch",
    "forum_url": "https://forum.defold.com/t/jerakins-editor-scripts/63840",
    "website_url": "",
    "platforms": [],
    "tags": [
        "editor script"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
@Jerakin wouldn't it make sense to include this in the Monarch repo instead?

**Comment by Jerakin** [comment]
Yeah, I would think so. Thought if that is the case I think it would be good too get a second opinion to what is implied in this one.
i.e. Here I presume that a user will create a gui scene first. But maybe it is more common to create the collection. The files are created next to the gui scene, but maybe they should all be put into a subfolder. Before it's accepted as the "standard", it would be nice to know if it actually makes sense to more than just me to work in this way.

**Comment by britzl** [comment]
I'm also thinking that you'd start with the gui scene. To me it makes the most sense to build the visual representation of the Monarch screen first, then the collection etc.

Creating the files next to the gui scene also makes sense I think.

**Comment by Jerakin** [comment]
There was no other opinion on Slack when I asked too, so I will close this and put it straight into Monarch then.
