### ISSUE TITLE
Apple Spider

### ISSUE THREAD

**Issue by SkaterDad** [defold/awesome-defold#122]
I'm honestly surprised I didn't do this yet!

Original release in August 2020 for Android.  iOS release date January 2023.

I can tone down the vibrancy of that 'full' graphic if needed.

```json
{
    "name": "Apple Spider",
	"description": "Spiders are attacking the apple orchard! Attack!",
    "url": "https://apps.apple.com/app/id6444730092",
    "developer": "Skater Dad Games",
    "publisher": "",
    "releasedate": "August 2020",
    "platforms": "iOS,Android",
    "images": {
        "full": "https://user-images.githubusercontent.com/13255599/215679693-6c1e119f-50bd-44b1-ac0a-33781f4c046d.png",
        "half": "https://user-images.githubusercontent.com/13255599/215679698-29e83aa0-4467-42e3-8271-22f9f7f83792.png",
        "third": "https://user-images.githubusercontent.com/13255599/215679691-3cb3adf4-b8d0-4d4c-a950-8b9cb51cf4d8.png"
    }
}
```

![apple-spider-third](https://user-images.githubusercontent.com/13255599/215679691-3cb3adf4-b8d0-4d4c-a950-8b9cb51cf4d8.png)
![apple_spider_full](https://user-images.githubusercontent.com/13255599/215679693-6c1e119f-50bd-44b1-ac0a-33781f4c046d.png)
![apple-spider-half](https://user-images.githubusercontent.com/13255599/215679698-29e83aa0-4467-42e3-8271-22f9f7f83792.png)

**Comment by britzl** [comment]
Thanks! It will be added to the website later today.
