### ISSUE TITLE
DEFinitely-Lit

### ISSUE THREAD

**Issue by Caue-Aron** [defold/awesome-defold#126]
Optionally also attach two images ![image](https://user-images.githubusercontent.com/54822334/221260125-2cc91604-f3fd-49e7-96da-5e30237cef33.png).
{
    "name": "DEFinitely-Lit",
    "description": "The quickest way to lit up your scene in Defold! Bring a sun and light sources to your scene and apply lighting scripts to your object to bring light into your game!",
    "license": "Unlicensed",
    "author": "Arônimo",
    "library_url": "https://github.com/Caue-Aron/DEFifnitely-Lit/archive/refs/tags/1.1.zip",
    "project_url": "https://github.com/Caue-Aron/DEFifnitely-Lit",
    "forum_url": "https://forum.defold.com/t/new-definitely-lit-extension-now-on-1-4/72569?u=caue-aron",
    "website_url": "",
    "platforms": [
        "windows"
    ],
    "tags": [
        "rendering",
        "shaders"
    ],
    "images": {
        "hero": "
![image](https://user-images.githubusercontent.com/54822334/221260178-0e3ef7bb-be0a-4df5-9a52-df9c3555494e.png)
",
        "thumb": "
![image](https://user-images.githubusercontent.com/54822334/221260191-f6a7d883-0ab1-4bbe-a919-58aca60e0e87.png)
"
    }
}

**Comment by britzl** [comment]
Thank you! Added: https://github.com/defold/awesome-defold/commit/15c9f313c6ebc7efa8a79803ab0f6fbf7db9a973
