### ISSUE TITLE
editor-script-components

### ISSUE THREAD

**Issue by Jerakin** [defold/awesome-defold#13]
![editor-script-components-thumb](https://user-images.githubusercontent.com/5273682/72210828-72f1c080-34c1-11ea-8370-5bf4e666776c.png)
![editor-script-components-hero](https://user-images.githubusercontent.com/5273682/72210829-72f1c080-34c1-11ea-94ee-d92c2e548bd1.png)

{
    "name": "editor-script-components",
    "description": "This script adds a menu items in the outline to create new resources depending on your selection. ",
    "license": "MIT License",
    "author": "Jerakin",
    "library_url": "https://github.com/Jerakin/editor-script-components/archive/master.zip",
    "project_url": "https://github.com/Jerakin/editor-script-components",
    "forum_url": "https://forum.defold.com/t/jerakins-editor-scripts/63840",
    "website_url": "",
    "platforms": [],
    "tags": [
        "editor script"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Added in commit https://github.com/defold/awesome-defold/commit/7575cabe4069bd525cfa7d56981b4ee72e1315e2
