### ISSUE TITLE
Rocket Run

### ISSUE THREAD

**Issue by tomhcrazy** [defold/awesome-defold#130]
```json
{
    "name": "Rocket Run",
	"description": "Rocket Run is a thrilling exploration game where players navigate their spaceship through various levels. Featuring retro graphics and engaging gameplay, players collect artifacts while avoiding deadly sentries targeting their ship. Players must monitor their shields and fuel to ensure they don't run out. Can you conquer Rocket Run?",
    "url": "https://www.crazygames.com/game/rocket-run",
    "developer": "Ben James",
    "publisher": "CrazyGames",
    "releasedate": "February 2019",
    "platforms": "CrazyGames, HTML5",
    "images": {
        "full": "![rocket-run-full](https://user-images.githubusercontent.com/128033392/225955140-c3c0c3fe-2b02-4d12-99a2-c15e3e98ee2c.png)",
        "half": "![rocket-run-half](https://user-images.githubusercontent.com/128033392/225956375-90ded0dc-4772-458a-9f8c-763444f8022f.png)",
        "third": "![rocket-run-third](https://user-images.githubusercontent.com/128033392/225956479-06bfa839-7577-4409-a8a2-03bde13b63c9.png)"
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page

**Comment by britzl** [comment]
@tomhcrazy Thank you for the submission. Could you please update the screenshots to show gameplay instead of a menu screen?

**Comment by neonlifes** [comment]
Hi @britzl 
I tried to make the images in two sizes (half, third). Hope it turned out well.
![rocketrun-half](https://user-images.githubusercontent.com/70640955/226134090-2dbc1a20-def5-49f0-adca-0b074edc3c98.png)
![rocketrun-third](https://user-images.githubusercontent.com/70640955/226134096-7d102e0b-725c-4496-9082-72e0d20024e3.png)

**Comment by britzl** [comment]
@neonlifes Thanks!
