### ISSUE TITLE
Rocket Run is not visible on the Showcase page

### ISSUE THREAD

**Issue by neonlifes** [defold/awesome-defold#133]
Hi @britzl 
For some reason recently added game Rocket Run is not visible on the Showcase page.

**Comment by britzl** [comment]
Ah,  yes, once it is added to this repo it will trigger a site rebuild. The site rebuild will import assets and games, and once we have these added to the website we can also assign how the games should be shown. I've done this for Rocket Run now:

https://github.com/defold/defold.github.io/commit/cf95291589afd0765aa2e65bde78e0cfc55d3072

**Comment by neonlifes** [comment]
Thanks @britzl 

> Ah, yes, once it is added to this repo it will trigger a site rebuild. The site rebuild will import assets and games, and once we have these added to the website we can also assign how the games should be shown.

That is, I understand correctly that for the game to appear on the Showcase page, this must be specified manually?

**Comment by neonlifes** [comment]
> Correct, it is a manual step.

Thanks @britzl 

Also now I went to the page and the image for the game is not displayed. There seems to be an error in the name of the images.

**Comment by britzl** [comment]
Oh, I named two of the images rocker-run and not rocket-run! :-) Fixed now. New site should be up soon.

**Comment by neonlifes** [comment]
> Oh, I named two of the images rocker-run and not rocket-run! :-) Fixed now. New site should be up soon.

@britzl Ok, thanks!
