### ISSUE TITLE
Defold Yoga

### ISSUE THREAD

**Issue by farism** [defold/awesome-defold#135]
Optionally also attach two images Defold Yoga-hero.[png|jpg] (max 2400x666) and Defold Yoga-thumb.[png|jpg] (max 580x380).
{
    "name": "Defold Yoga",
    "description": "A Defold native extension exposing Facebook's Yoga layout library via a Lua wrapper.",
    "license": "MIT",
    "author": "Faris Mustafa",
    "library_url": "https://github.com/farism/defold-yoga",
    "project_url": "https://github.com/farism/defold-yoga",
    "forum_url": "",
    "website_url": "https://github.com/farism/defold-yoga",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "gui",
        "rendering"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thank you!

Closed via: https://github.com/defold/awesome-defold/commit/4213553880f7a0df064a3cbe74ba8379206a4e1d
