### ISSUE TITLE
Apple GameKit Game Center

### ISSUE THREAD

**Issue by animonger** [defold/awesome-defold#15]
Optionally also attach two images Apple GameKit Game Center-hero.[png|jpg] (max 2400x666) and Apple GameKit Game Center-thumb.[png|jpg] (max 580x380).
{
    "name": "Apple GameKit Game Center",
    "description": "Apple GameKit Game Center extension.",
    "license": "MIT License",
    "author": "Warren Fuller",
    "library_url": "https://github.com/animonger/extension-gamekit/archive/master.zip",
    "project_url": "https://github.com/animonger/extension-gamekit",
    "forum_url": "https://forum.defold.com/t/apple-gamekit-game-center-extension/64372",
    "website_url": "",
    "platforms": [
        "ios",
        "macos"
    ],
    "tags": [
        "social"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thanks!
