### ISSUE TITLE
Defold Tilemap Animator

### ISSUE THREAD

**Issue by planksoftware** [defold/awesome-defold#18]
Optionally also attach two images Defold Tilemap Animator-hero.[png|jpg] (max 2400x666) and Defold Tilemap Animator-thumb.[png|jpg] (max 580x380).
{
    "name": "Defold Tilemap Animator",
    "description": "Defold Tilemap Animator (DTA) allows for easy runtime tile animations in a Defold game engine project.",
    "license": "MIT License",
    "author": "Klayton Kowalski",
    "library_url": "https://github.com/planksoftware/defold-tilemap-animator/archive/master.zip",
    "project_url": "https://github.com/planksoftware/defold-tilemap-animator",
    "forum_url": "",
    "website_url": "planksoftware.com",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "animation"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thank you! https://github.com/defold/awesome-defold/blob/master/assets/tilemapanimator.json
