### ISSUE TITLE
DefGraph

### ISSUE THREAD

**Issue by dev-masih** [defold/awesome-defold#2]
Optionally also attach two images DefGraph-hero.[png|jpg] (max 2400x666) and DefGraph-thumb.[png|jpg] (max 580x380).
{
    "name": "DefGraph",
    "description": "This module contains functions to create a world map as a shape of a graph and the ability to manipulate it at any time, easily see debug drawing of this graph and move go's inside of this graph with utilizing auto pathfinder.",
    "license": "CC0 1.0 Universal",
    "author": "dev-masih",
    "library_url": "",
    "project_url": "https://github.com/dev-masih/defgraph",
    "forum_url": "https://forum.defold.com/t/defgraph/63617",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "ai",
        "code samples",
        "math"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

![DefGraph-hero](https://user-images.githubusercontent.com/8469800/66703317-337ad300-ed1e-11e9-90eb-f2c4d25e0968.jpg)
![DefGraph-thumb](https://user-images.githubusercontent.com/8469800/66703318-34136980-ed1e-11e9-8371-06549b15e596.jpg)

**Comment by britzl** [comment]
Added: https://github.com/defold/awesome-defold/commit/0f33e11f9f0e14b31f1174a5516602d86342c62e
