### ISSUE TITLE
Defold Simple Platformer

### ISSUE THREAD

**Issue by planksoftware** [defold/awesome-defold#20]
Optionally also attach two images Defold Simple Platformer-hero.[png|jpg] (max 2400x666) and Defold Simple Platformer-thumb.[png|jpg] (max 580x380).
{
    "name": "Defold Simple Platformer",
    "description": "Defold Simple Platformer (DSP) provides elementary physics logic to a Defold game engine project.",
    "license": "MIT License",
    "author": "Klayton Kowalski",
    "library_url": "https://github.com/planksoftware/defold-simple-platformer",
    "project_url": "https://github.com/planksoftware/defold-simple-platformer/archive/master.zip",
    "forum_url": "https://forum.defold.com/t/defold-simple-platformer/64668",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "physics",
        "platform"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thank you. Added: https://github.com/defold/awesome-defold/blob/master/assets/defoldsimpleplatformer.json
