### ISSUE TITLE
Color Lib

### ISSUE THREAD

**Issue by y444** [defold/awesome-defold#21]
Optionally also attach two images Color Lib-hero.[png|jpg] (max 2400x666) and Color Lib-thumb.[png|jpg] (max 580x380).
{
    "name": "Color Lib",
    "description": "Enable defining colors in a more traditional hex format. Has presets of all the named web colors. Allows to create your own named colors.",
    "license": "CC0",
    "author": "y444",
    "library_url": "https://github.com/y444/defold-color-lib/archive/master.zip",
    "project_url": "https://github.com/y444/defold-color-lib",
    "forum_url": "",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "util"
    ],
    "images": {
        "hero": "Color Lib-hero.jpg",
        "thumb": "Color Lib-thumb.jpg"
    }
}
![Color Lib-hero](https://user-images.githubusercontent.com/2448030/77831097-12783400-713e-11ea-84de-9475e66fb8d7.jpg)
![Color Lib-thumb](https://user-images.githubusercontent.com/2448030/77831098-13a96100-713e-11ea-9af9-b07d323261ca.jpg)

**Comment by britzl** [comment]
Thank you for the contribution! It should be available within a few minutes.
