### ISSUE TITLE
Druid

### ISSUE THREAD

**Issue by Insality** [defold/awesome-defold#22]
Optionally also attach two images Druid-hero.[png|jpg] (max 2400x666) and Druid-thumb.[png|jpg] (max 580x380).
{
    "name": "Druid",
    "description": "Druid - powerful Defold component UI library. Use basic Druid components or make your own game-specific components to make amazing GUI in your games",
    "license": "MIT",
    "author": "Insality",
    "library_url": "https://github.com/Insality/druid/archive/master.zip",
    "project_url": "https://github.com/Insality/druid",
    "forum_url": "https://forum.defold.com/t/druid-component-gui-library/64857",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "gui",
        "input",
        "system"
    ],
    "images": {
        "hero": "https://github.com/Insality/druid/raw/develop/media/druid_logo.png",
        "thumb": "https://raw.githubusercontent.com/Insality/druid/develop/media/druid_thumb_logo.png"
    }
}

**Comment by britzl** [comment]
Thanks. Added. It should be available in the Asset Portal in a few minutes.
