### ISSUE TITLE
MiraState

### ISSUE THREAD

**Issue by stepism** [defold/awesome-defold#23]
Optionally also attach two images MiraState-hero.[png|jpg] (max 2400x666) and MiraState-thumb.[png|jpg] (max 580x380).
{
    "name": "MiraState",
    "description": "hierarchical State Machine.",
    "license": "CC0",
    "author": "kazupon",
    "library_url": "https://github.com/stepism/defold-mira-substate/archive/master.zip",
    "project_url": "https://github.com/stepism/defold-mira-substate",
    "forum_url": "",
    "website_url": "https://kazupon.org",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "system"
    ],
    "images": {
        "hero": "https://github.com/stepism/defold-mira-substate/blob/master/raw/defold-asset-header.png",
        "thumb": "https://github.com/stepism/defold-mira-substate/blob/master/raw/defold-asset-logo.png"
    }
}

**Comment by britzl** [comment]
Thank you!

**Comment by stepism** [comment]
@britzl 
Thank you!

If everything is ok, here are the hero and thumb images. I am happy if you apply it.

![MiraState-hero](https://user-images.githubusercontent.com/41262965/80943489-4b34b880-8e22-11ea-98d4-9c6e287779ad.png)

![MiraState-thumb](https://user-images.githubusercontent.com/41262965/80943493-4ff96c80-8e22-11ea-82d8-784ee8f0fdec.png)

**Comment by britzl** [comment]
Thanks. I've added them They should be visible on the site in a minute or two.

**Comment by stepism** [comment]
Thank you! I was able to confirm.
