### ISSUE TITLE
DSFonts

### ISSUE THREAD

**Issue by sergeysinyavsky** [defold/awesome-defold#24]
Optionally also attach two images DSFonts-hero.[png|jpg] (max 2400x666) and DSFonts-thumb.[png|jpg] (max 580x380).
{
    "name": "DSFonts",
    "description": "This is a set of shaders and materials for the distance field fonts.",
    "license": "MIT License",
    "author": "Sergey Sinyavsky",
    "library_url": "https://github.com/sergeysinyavsky/dsfonts/archive/master.zip",
    "project_url": "https://github.com/sergeysinyavsky/dsfonts",
    "forum_url": "https://forum.defold.com/t/dsfonts-shader-set/65066",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "fonts",
        "shaders"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by sergeysinyavsky** [comment]
![dsfonts](https://user-images.githubusercontent.com/12486956/81418865-05dff600-9156-11ea-86ec-193e56469892.png)

**Comment by britzl** [comment]
Thank you! https://defold.com/assets/dsfonts
