### ISSUE TITLE
ZOOM-BE

### ISSUE THREAD

**Issue by flazm** [defold/awesome-defold#25]
```json
{
    "name": "ZOOM-BE",
	"description": "Zoom-Be is a collaborative platformer in which you help two memorable zombie characters escape an evil facility using a little bit of logic and the magic of friendship. Help Zoom and Be avoid traps, destroy objects, solve puzzles and carry each other to freedom - literally!",
    "url": "https://poki.com/en/g/zoom-be",
    "developer": "Flazm",
    "publisher": "Poki",
    "release_date": "May 2020",
    "platforms": "iOS,Android,HTML5,Poki",
    "images": {
        "full": "![zoom-be-full](https://user-images.githubusercontent.com/7146524/81439995-0093a300-9178-11ea-9ad4-17a4b9bba206.png)",
        "half": "![zoom-be-half](https://user-images.githubusercontent.com/7146524/81440008-04bfc080-9178-11ea-9530-cca2526c4c11.png)",
        "third": "![zoom-be-third](https://user-images.githubusercontent.com/7146524/81440010-05585700-9178-11ea-9227-f3e5658f802a.png)"
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page

**Comment by britzl** [comment]
Thanks! https://defold.com/showcase/
