### ISSUE TITLE
Narrator

### ISSUE THREAD

**Issue by astrochili** [defold/awesome-defold#31]
![narrator_2400](https://user-images.githubusercontent.com/4752473/85541861-28a06e00-b621-11ea-9013-d28710fc1ec5.jpg)
![narrator_580](https://user-images.githubusercontent.com/4752473/85541856-263e1400-b621-11ea-905b-6e30039c32b7.jpg)
{
    "name": "Narrator",
    "description": "The Ink language runtime. Narrator allows to convert Ink scripts to the book and play it as a story. Suitable for interactive fiction games, dialogues and complex narrative stories.\n\nRequired the LPeg extension.",
    "license": "MIT",
    "author": "Roman Silin",
    "library_url": "https://github.com/astrochili/narrator/archive/master.zip",
    "project_url": "https://github.com/astrochili/narrator",
    "forum_url": "https://forum.defold.com/t/narrator-the-ink-narrative-scripting-language-runtime/65653",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "game mechanic"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thanks!

**Comment by astrochili** [comment]
Looks like the asset is created and listed on the assets page but the details page is blank.

https://defold.com/assets/narrator/

**Comment by britzl** [comment]
Ah, yeah, found it. The `\n\n` in the description messed up the generated page.

**Comment by astrochili** [comment]
> Ah, yeah, found it. The `\n\n` in the description messed up the generated page.

Thank you!
