### ISSUE TITLE
Defold Colors

### ISSUE THREAD

**Issue by gymratgames** [defold/awesome-defold#36]
Optionally also attach two images Defold Colors-hero.[png|jpg] (max 2400x666) and Defold Colors-thumb.[png|jpg] (max 580x380).
{
    "name": "Defold Colors",
    "description": "Defold Colors (DC) provides customizable palettes and color utility features to a Defold game engine project.",
    "license": "AGPL-3.0 License",
    "author": "Klayton Kowalski",
    "library_url": "https://github.com/gymratgames/defold-colors/archive/master.zip",
    "project_url": "https://github.com/gymratgames/defold-colors",
    "forum_url": "https://forum.defold.com/t/defold-colors/65855",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "art assets",
        "rendering",
        "util"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thanks! https://github.com/defold/awesome-defold/blob/master/assets/defold-colors.json
