### ISSUE TITLE
Merge Shooter 2048

### ISSUE THREAD

**Issue by newangle-llc** [defold/awesome-defold#39]
```json
{
    "name": "Merge Shooter 2048",
	"description": "Tap the screen and take a shot. Trying to score high!",
    "url": "https://margeshooter2048.page.link/mVFa",
    "developer": "newangle.llc",
    "publisher": "",
    "release_date": "2020",
    "platforms": "Android",
    "images": {
        "full": "![game-name-full](https://user-images.githubusercontent.com/63034946/90307288-9d9c6f80-df0f-11ea-9b94-44402895adf1.png)",
        "half": "![game-name-half](https://user-images.githubusercontent.com/63034946/90307305-b3aa3000-df0f-11ea-852e-84c300567a2b.png)",
        "third": "![game-name-third](https://user-images.githubusercontent.com/63034946/90307311-ba38a780-df0f-11ea-97f7-6ee77ec8da51.png)"
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page

**Comment by britzl** [comment]
Thank you! Added file: https://github.com/defold/awesome-defold/blob/master/games/merge_shooter_2048.json

Will look into getting it on the Showcase page as well!
