### ISSUE TITLE
Def Vungle ads extension

### ISSUE THREAD

**Issue by SkaterDad** [defold/awesome-defold#46]
```json
{
    "name": "Def Vungle",
	"description": "Vungle interstitial and rewarded video ads support for Android & Amazon.",
    "license": "Apache 2.0",
    "tags": [
		"Ads",
		"Monetization"
    ],
    "author": "SkaterDad",
    "library_url": "https://github.com/SkaterDad/defold-vungle/archive/1.0.0.zip",
    "forum_url": "",
    "project_url": "https://github.com/SkaterDad/defold-vungle",
	"website_url": "",
    "platforms": [
        "Android"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold asset.
* `description` - (REQUIRED) Short text describing the asset.
* `license` - (OPTIONAL) The license used by the asset.
* `author` - (REQUIRED) Name of the extension author.
* `library_url` - (OPTIONAL) URL to add as Defold project dependency (eg https://github.com/britzl/monarch/archive/master.zip).
* `forum_url` - (OPTIONAL) URL to a Defold forum post for discussions about the asset.
* `project_url` - (OPTIONAL) URL to a website with additional information about the asset (eg https://github.com/britzl/monarch).
* `website_url` - (OPTIONAL) URL to a website with additional information.
* `tags` - (REQUIRED) One or more tags to categorize the asset.
* `platforms` - (REQUIRED) One or more platforms supported by the asset.
* `images` - (OPTIONAL) Filenames of two images that can be used when presenting the asset.
  * `hero` - (OPTIONAL) Filename of attached image to use as banner image. PNG or JPG. Recommended size is 2400x666.
  * `thumb` - (OPTIONAL) Filename of attached image to use as thumbnail image. PNG or JPG. Recommended size is 380x570 pixels.

Note: You must provide at least one of `library_url`, `website_url` and `project_url`.

**Comment by britzl** [comment]
Thank you!

https://github.com/defold/awesome-defold/blob/master/assets/defvungle.json
