### ISSUE TITLE
NavGO

### ISSUE THREAD

**Issue by DrCampbell2017** [defold/awesome-defold#47]
Optionally also attach two images NavGO-hero.[png|jpg] (max 2400x666) and NavGO-thumb.[png|jpg] (max 580x380).
{
    "name": "NavGO",
    "description": "NavGO is an easy to use path finding tool meant for use when tile map based path finding is just not possible or is to complicated for the project at hand,",
    "license": "MIT",
    "author": "gameoffate2018",
    "library_url": "https://github.com/DrCampbell2017/NavGO/archive/Alpha.3.zip",
    "project_url": "https://github.com/DrCampbell2017/NavGO",
    "forum_url": "",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "tools"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thank you: https://github.com/defold/awesome-defold/commit/3e02fdc47fc1a15a3d21d29cfcf534a3f1bf94db
