### ISSUE TITLE
Cafebazaar In-app purchases

### ISSUE THREAD

**Issue by dev-masih** [defold/awesome-defold#5]
{
    "name": "Cafebazaar In-app purchases",
    "description": "Defold native extension which provides access to In-app purchase functionality on Cafebazaar Android app store.",
    "license": "MIT License",
    "author": "dev-masih",
    "library_url": "",
    "project_url": "https://github.com/dev-masih/cafebazaar-iap",
    "forum_url": "https://forum.defold.com/t/cafebazaar-in-app-purchases/63756",
    "website_url": "",
    "platforms": [
        "android"
    ],
    "tags": [
        "Extensions",
	"System",
	"Monetization"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

![hero](https://user-images.githubusercontent.com/8469800/67614605-c1e65e80-f7cc-11e9-9f9d-e12a8cd9be04.jpg)
![thumb](https://user-images.githubusercontent.com/8469800/67614606-c27ef500-f7cc-11e9-9125-bb0180f3bc90.jpg)

**Comment by britzl** [comment]
Thanks! Added!
