### ISSUE TITLE
Poki SDK for Defold

### ISSUE THREAD

**Issue by AGulev** [defold/awesome-defold#55]
```json
{
    "name": "Poki SDK",
    "description": "Poki SDK native extension for Defold game engine",
    "license": "MIT License",
    "tags": [
		"Ads",
		"Social",
		"System",
    ],
    "author": "Alexey Gulev",
    "library_url": "https://github.com/AGulev/defold-poki-sdk/archive/main.zip",
    "forum_url": "https://forum.defold.com/t/poki-sdk-native-extension-for-defold/67019",
    "project_url": "https://github.com/AGulev/defold-poki-sdk",
	"website_url": "",
    "platforms": [
        "HTML5"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}
```
Images:
[Archive.zip](https://github.com/defold/awesome-defold/files/5690742/Archive.zip)

* `name` - (REQUIRED) Name of the awesome Defold asset.
* `description` - (REQUIRED) Short text describing the asset.
* `license` - (OPTIONAL) The license used by the asset.
* `author` - (REQUIRED) Name of the extension author.
* `library_url` - (OPTIONAL) URL to add as Defold project dependency (eg https://github.com/britzl/monarch/archive/master.zip).
* `forum_url` - (OPTIONAL) URL to a Defold forum post for discussions about the asset.
* `project_url` - (OPTIONAL) URL to a website with additional information about the asset (eg https://github.com/britzl/monarch).
* `website_url` - (OPTIONAL) URL to a website with additional information.
* `tags` - (REQUIRED) One or more tags to categorize the asset.
* `platforms` - (REQUIRED) One or more platforms supported by the asset.
* `images` - (OPTIONAL) Filenames of two images that can be used when presenting the asset.
  * `hero` - (OPTIONAL) Filename of attached image to use as banner image. PNG or JPG. Recommended size is 2400x666.
  * `thumb` - (OPTIONAL) Filename of attached image to use as thumbnail image. PNG or JPG. Recommended size is 380x570 pixels.

Note: You must provide at least one of `library_url`, `website_url` and `project_url`.

**Comment by britzl** [comment]
Thanks!

https://github.com/defold/awesome-defold/blob/master/assets/poki.json
