### ISSUE TITLE
Dicebag

### ISSUE THREAD

**Issue by 8bitskull** [defold/awesome-defold#56]
Optionally also attach two images Dicebag-hero.[png|jpg] (max 2400x666) and Dicebag-thumb.[png|jpg] (max 580x380).
{
    "name": "Dicebag",
    "description": "A module of probability functions designed specifically for games.\n\nInspired by this excellent blog post: https://www.redblobgames.com/articles/probability/damage-rolls.html",
    "license": "CC0 1.0 Universal",
    "author": "8BitSkull",
    "library_url": "",
    "project_url": "https://github.com/8bitskull/dicebag/tree/master",
    "forum_url": "https://forum.defold.com/t/dicebag-probability-for-games/67169",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "game mechanic",
        "math",
        "util"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thank you!

https://github.com/defold/awesome-defold/commit/78475310ba966a37e97a8e327037ad41cb469acd
