### ISSUE TITLE
Android Battery Status Extension

### ISSUE THREAD

**Issue by ultimateprogramer** [defold/awesome-defold#57]
Allows the developer to get Battery Charge & Charging Status on Android.

Extension is available at: 

[https://github.com/ahmedmaawy/defold-extension-battery](https://github.com/ahmedmaawy/defold-extension-battery)

To install the extension, add the following URL to your dependencies: 

[https://github.com/ahmedmaawy/defold-extension-battery/archive/v0.3.zip](https://github.com/ahmedmaawy/defold-extension-battery/archive/v0.3.zip)

## Exposed functions

* `battery.percentage()` - Integer value of the percentage of charge.
* `battery.is_charging()` - Boolean status of whether charging or not.

## GUI Example

A GUI example is found in the extension repository and this is how it renders out:

![Screenshot](https://github.com/ahmedmaawy/defold-extension-battery/raw/master/docs/extension-android-battery.jpeg)

**Comment by britzl** [comment]
Thank you fro submitting an asset. Could you please create an issue according to the following template:

https://github.com/defold/awesome-defold/issues/new?assignees=&labels=&template=new-asset.md&title=

Fill out the fields of the json file with the data required. Take a look at an existing asset if you are uncertain (https://github.com/defold/awesome-defold/tree/master/assets).

You can also fill out this form if that is more convenient: https://defold.com/submit_asset/

**Comment by ultimateprogramer** [comment]
Done.. thanks

**Comment by ultimateprogramer** [comment]
@britzl I had filled in the form on [https://defold.com/submit_asset/](https://defold.com/submit_asset/) but for some reason it didn't prefill the GitHub Issue ticket with the fields in the form. So I was left clueless what to do.
