### ISSUE TITLE
SpaceboomX

### ISSUE THREAD

**Issue by lharder** [defold/awesome-defold#59]
```json
{
   "name": "SpaceboomX",
	"description": "A frantic sidescrolling shooter that throws wave after wave of hideous, alien foes at you, while you collect precious minerals, evade whirling asteroids and blast your way through a barrage of enemy fire. You discover new technologies and equip increasingly better and bigger ships with faster engines, heavier armor, tougher shields, smarter sensors and more powerful guns and missiles. Play for free - free as in 'no ads', 'no in-app sales', just plain fun!",
   "url": "https://apps.apple.com/de/app/spaceboomx/id1543264384?l=en",
   "developer": "Lutz Harder",
   "publisher": "Lunius Entertainment",
   "release_date": "Jan 2020",
   "platforms": "iOS",
   "images": {
       "full": "spaceboomx-full.png",
       "half": "spaceboomx-half.png",
       "third": "spaceboomx-third.png"
   }
}
```
<img width="1680" alt="spaceboomx-full" src="https://user-images.githubusercontent.com/1334389/105523066-3ebcfc80-5cde-11eb-9b56-d95f341b4db0.png">
<img width="600" alt="spaceboomx-half" src="https://user-images.githubusercontent.com/1334389/105523097-48defb00-5cde-11eb-98c1-7576b720fc7c.png">
<img width="1680" alt="spaceboomx-third" src="https://user-images.githubusercontent.com/1334389/105523248-79bf3000-5cde-11eb-8f6c-15271dd8d153.png">

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page

**Comment by britzl** [comment]
https://github.com/defold/awesome-defold/commit/adf3af4f7c32fec2328d1ced12e23bed62954137
