### ISSUE TITLE
Facebook Ads (Audience Network) 

### ISSUE THREAD

**Issue by MrZak-dev** [defold/awesome-defold#60]
Optionally also attach two images Facebook Ads (Audience Network) -hero.[png|jpg] (max 2400x666) and Facebook Ads (Audience Network) -thumb.[png|jpg] (max 580x380).
{
    "name": "Facebook Ads (Audience Network) ",
    "description": "Facebook Audience Network Android Android extension",
    "license": "Apache License",
    "author": "MrZak-dev",
    "library_url": "",
    "project_url": "https://github.com/MrZak-dev/defold-facebook-ads",
    "forum_url": "https://forum.defold.com/t/facebook-ads-audience-network-extension/",
    "website_url": "",
    "platforms": [
        "android"
    ],
    "tags": [
        "ads",
        "monetization"
    ],
    "images": {
        "hero": "https://drive.google.com/uc?id=1jAWRV-x1ztq3XDh12ugUbcRlCPtB5uDX",
        "thumb": "https://drive.google.com/uc?id=1jAWRV-x1ztq3XDh12ugUbcRlCPtB5uDX"
    }
}

**Comment by britzl** [comment]
Thanks!

https://github.com/defold/awesome-defold/commit/963db377d6eea005cb9a54989a19cf7ef212546c
