### ISSUE TITLE
The Belt

### ISSUE THREAD

**Issue by ttblue1972** [defold/awesome-defold#62]
```json
{
    "name": "The Belt",
	"description": "As commander of an elite air force combat space ship you enter the asteroid field to collect minerals. Whilst collecting minerals and weapon powerups you will find that alien races already occupy and defend their claim to ownership of the asteroid fields.
Your survival depends on defeating the waves of enemies and bosses that the invaders from another galaxy send at you.",
    "url": "https://play.google.com/store/apps/details?id=com.qiccoding.uk.ltd
)
",
    "developer": "tremorBlue",
    "publisher": "",
    "releasedate": "2021",
    "platforms": "Android,HTML5,GameDistribution",
    "images": {
        "full": "![3000x750](https://user-images.githubusercontent.com/67410986/107935817-c9111d00-6f79-11eb-867e-b4284b55779f.png",
        "half": "
![1200x600](https://user-images.githubusercontent.com/67410986/107936823-04601b80-6f7b-11eb-9879-9e00f8c7ad7f.png)
",
        "third": "
![800x600](https://user-images.githubusercontent.com/67410986/107937699-2f973a80-6f7c-11eb-9a7f-fb0731c81d52.png)
"
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page

**Comment by britzl** [comment]
Thank you! The game will show up in the showcase page soon.

**Comment by ttblue1972** [comment]
My game was added to show case.. thankyou.. btw an error was made in the naming of the file.. expected the_belt-third.png and actual the-belt-third.png .. hence the image is not displaying.

**Comment by britzl** [comment]
Oh, good catch! I've updated the game listing. The new page should be visible soon.
