### ISSUE TITLE
defold-cairo

### ISSUE THREAD

**Issue by dlannan** [defold/awesome-defold#63]
Optionally also attach two images defold-cairo-hero.[png|jpg] (max 2400x666) and defold-cairo-thumb.[png|jpg] (max 580x380).
{
    "name": "defold-cairo",
    "description": "Cairo extension for Defold for developing UI widgets. Many widgets included already.",
    "license": "MIT",
    "author": "David Lannan",
    "library_url": "",
    "project_url": "https://github.com/dlannan/defold-cairo",
    "forum_url": "",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "gui"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thank you! https://defold.com/assets/defold-cairo/

Will you also announce this on the Defold forum?

**Comment by dlannan** [comment]
Sure will do. Its very early build but happy to share.

**Comment by dlannan** [comment]
Sure. Might clean it up a little if you want :)

**Comment by britzl** [comment]
> Sure. Might clean it up a little if you want :)

I don't think that's needed, but it is up to you. We're sending a newsletter on Monday, but I will not include anything about Cairo in that letter. More likely to be included in the next one after that (in two weeks).
