### ISSUE TITLE
Defold Screen Manager

### ISSUE THREAD

**Issue by klaytonkowalski** [defold/awesome-defold#64]
Optionally also attach two images Defold Screen Manager-hero.[png|jpg] (max 2400x666) and Defold Screen Manager-thumb.[png|jpg] (max 580x380).
{
    "name": "Defold Screen Manager",
    "description": "Defold Screen Manager (dscreen) provides a game state management system in a Defold game engine project.",
    "license": "MIT License",
    "author": "Klayton Kowalski",
    "library_url": "https://github.com/klaytonkowalski/defold-screen-manager",
    "project_url": "https://github.com/klaytonkowalski/defold-screen-manager/archive/main.zip",
    "forum_url": "https://forum.defold.com/t/defold-screen-manager/67830",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "gui"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thanks! https://github.com/defold/awesome-defold/blob/master/assets/defold-screen-manager.json
