### ISSUE TITLE
Solitaire Jazz Travel

### ISSUE THREAD

**Issue by BigButtonCo** [defold/awesome-defold#69]
```json
{
    "name": "Solitaire Jazz Travel",
	"description": "Train your brain by solving card puzzles in our Solitaire Jazz Travel game! Do you enjoy playing solitaire games but in bored of many similar card games like Freecell, Hearts, Spider, Tripeaks, Club, Diamond, Pyramid, Golf or Mahjong? In this case, our solitaire card puzzle game is just right for you!",
    "url": "https://www.bigbutton.co/solitaire-jazz-travel",
    "developer": "BigButton Co Sp.z o.o.",
    "publisher": "BigButton Co Sp.z o.o.",
    "releasedate": "April 2021",
    "platforms": "iOS,Android,HTML5",
    "images": {
        "full": "game-name-full.png",
        "half": "game-name-half.png",
        "third": "game-name-third.png"
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page
![game-name-full](https://user-images.githubusercontent.com/79597961/121073097-6666ba00-c7d2-11eb-974a-c369b6bbec13.png)
![game-name-half](https://user-images.githubusercontent.com/79597961/121073104-68c91400-c7d2-11eb-911f-864bf26eec78.png)
![game-name-third](https://user-images.githubusercontent.com/79597961/121073108-6961aa80-c7d2-11eb-9391-8da58da23619.png)

**Comment by britzl** [comment]
Thank you!
