### ISSUE TITLE
trunner asset pack

### ISSUE THREAD

**Issue by Khhs167** [defold/awesome-defold#7]
Optionally also attach two images trunner asset pack-hero.[png|jpg] (max 2400x666) and trunner asset pack-thumb.[png|jpg] (max 580x380).
{
    "name": "trunner asset pack",
    "description": "A t-rex run asset pack",
    "license": "No license",
    "author": "khhs",
    "library_url": "https://khhs.itch.io/trunner-asset-pack/download/eyJleHBpcmVzIjoxNTcyODA0NjQ4LCJpZCI6NDY4MTk5fQ%3d%3d.MtiVk%2b%2bIj5vYntoDDzTvggnaYOU%3d",
    "project_url": "https://khhs.itch.io/trunner-asset-pack",
    "forum_url": "https://itch.io/t/597080/forum",
    "website_url": "https://khhs.itch.io/trunner-asset-pack",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "html5"
    ],
    "tags": [
        "art assets"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
You need to specify a license for the use of your asset. Please also make sure that the artwork is actually yours as it looks very similar to the original Google T-Rex easter egg.

**Comment by britzl** [comment]
No reply in months. Closing.
