### ISSUE TITLE
3DModelsCC0

### ISSUE THREAD

**Issue by nisuaia** [defold/awesome-defold#72]
Optionally also attach two images 3DModelsCC0-hero.[png|jpg] (max 2400x666) and 3DModelsCC0-thumb.[png|jpg] (max 580x380).
{
    "name": "3DModelsCC0",
    "description": "Library of public domain 3D models. Available for everyone. No need for credit or attribution even if used commercially.",
    "license": "CC0",
    "author": "Nisu",
    "library_url": "https://www.3dmodelscc0.com/",
    "project_url": "https://www.3dmodelscc0.com/",
    "forum_url": "",
    "website_url": "https://www.3dmodelscc0.com/",
    "platforms": [
        "macos",
        "windows",
        "linux"
    ],
    "tags": [
        "art assets"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thank you: https://github.com/defold/awesome-defold/commit/9d0d84c01813bd52505eefe07b15c5b299d4519e
