### ISSUE TITLE
DefArmy

### ISSUE THREAD

**Issue by dev-masih** [defold/awesome-defold#8]
Optionally also attach two images DefArmy-hero.[png|jpg] (max 2400x666) and DefArmy-thumb.[png|jpg] (max 580x380).
{
    "name": "DefArmy",
    "description": "This module helps you to create groups (army) of game objects (soldiers) and organize them in several different patterns or your customized pattern and manage moving and rotating game objects as a customizable group.",
    "license": "MIT License",
    "author": "dev-masih",
    "library_url": "",
    "project_url": "https://github.com/dev-masih/defarmy",
    "forum_url": "https://forum.defold.com/t/defarmy/63818",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "ai",
        "code samples",
        "extensions",
        "math"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

![hero](https://user-images.githubusercontent.com/8469800/68103167-efc55480-feea-11e9-852a-5d35ec045e45.jpg)
![thumb](https://user-images.githubusercontent.com/8469800/68103168-efc55480-feea-11e9-80c6-36fb800ccd7f.jpg)

**Comment by britzl** [comment]
Thanks! Added.
