### ISSUE TITLE
trickortreat

### ISSUE THREAD

**Issue by FlexYourBrain** [defold/awesome-defold#81]
Optionally also attach two images trickortreat-hero.[png|jpg] (max 2400x666) and trickortreat-thumb.[png|jpg] (max 580x380).
{
    "name": "TrickOrTreat",
    "description": "Fun and Free Halloween themed art asset pack.",
    "license": "CC0 1.0 Universal",
    "author": "Agustin R.",
    "library_url": "",
    "project_url": "https://github.com/FlexYourBrain/TrickOrTreat",
    "forum_url": "",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "animation",
        "art assets"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
![trickortreat-thumb](https://user-images.githubusercontent.com/28400489/139556339-a37b6e35-a341-499f-ab96-978a9d2cfc76.png)
![trickortreat-hero](https://user-images.githubusercontent.com/28400489/139556340-2f65fa9a-7fc5-46ce-9d75-153d735d95bb.jpg)

}

**Comment by britzl** [comment]
Thank you!
