### ISSUE TITLE
BoxRob

### ISSUE THREAD

**Issue by flazm** [defold/awesome-defold#83]
```json
{
    "name": "BoxRob",
	"description": "",
    "url": "https://poki.com/en/g/boxrob",
    "developer": "7Spot Games",
    "publisher": "",
    "releasedate": "November 1, 2021",
    "platforms": "Poki",
    "images": {
        "full": "https://user-images.githubusercontent.com/7146524/141499159-6dabb981-ccad-4f57-b57f-baf0a7565e3e.png",
        "half": "https://user-images.githubusercontent.com/7146524/141499193-006d1acd-833b-47f2-881e-3986e916ea9b.png",
        "third": "https://user-images.githubusercontent.com/7146524/141499225-2e1a723b-2d16-4971-b70c-ead72a4cd9b2.png"
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page

**Comment by britzl** [comment]
Thanks!
