### ISSUE TITLE
Color Guys

### ISSUE THREAD

**Issue by Gabritz** [defold/awesome-defold#84]
```json
{
    "name": "Color Guys",
    "description": "Pink Guy was kidnapped by a giant bat, now the Color Guys need your help to rescue him. Get ready to embark on an epic rescue mission full of challenges and puzzles.",
    "url": "https://store.steampowered.com/app/1762490/Color_Guys/",
    "developer": "Gabriel Almeida",
    "publisher": "Gabriel Almeida",
    "releasedate": "October 20, 2021",
    "platforms": "Windows,Steam",
    "images": {
        "full": "![color-guys-full](https://user-images.githubusercontent.com/91931446/146140098-aa6362b1-593e-4ffa-9315-01cf423525b6.png)",
        "half": "![color-guys-half](https://user-images.githubusercontent.com/91931446/146140194-64280fab-4103-498b-aca7-96630af8eb7b.png)",
        "third": "![color-guys-third](https://user-images.githubusercontent.com/91931446/146140271-8313a642-b66f-4925-9121-0eb7c00c3a99.png)"
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page

**Comment by britzl** [comment]
Thanks! The game will be up on the site soon!
