### ISSUE TITLE
Horri-Fold

### ISSUE THREAD

**Issue by TheKing0x9** [defold/awesome-defold#87]
Optionally also attach two images Horri-Fold-hero.[png|jpg] (max 2400x666) and Horri-Fold-thumb.[png|jpg] (max 580x380).
{
    "name": "Horri-Fold",
    "description": "A Lo-Fi Horror shader.",
    "license": "MIT License",
    "author": "TheKing0x9",
    "library_url": "https://github.com/TheKing0x9/horri-fold/archive/main.zip",
    "project_url": "https://github.com/TheKing0x9/horri-fold",
    "forum_url": "https://forum.defold.com/t/horri-fold-a-lo-fi-horror-shader-for-defold/70090",
    "website_url": "https://theking0x9.itch.io/horri-fold",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "rendering",
        "shaders"
    ],
    "images": {
        "hero": "
![Horri-Fold-hero](https://user-images.githubusercontent.com/33807516/148945314-9a32a676-96bb-4db9-82e5-0e0224b3e506.png)
",
        "thumb": "
![Horri-Fold-thumb](https://user-images.githubusercontent.com/33807516/148944695-3903039b-f062-450a-993b-82ec2ac1a81d.png)
"
    }
}

**Comment by britzl** [comment]
Thanks!

https://github.com/defold/awesome-defold/commit/b9949a132414fad87af9c0eede60144d39965afe
