### ISSUE TITLE
GameScore

### ISSUE THREAD

**Issue by megalanthus** [defold/awesome-defold#89]
Optionally also attach two images GameScore-hero.[png|jpg] (max 2400x666) and GameScore-thumb.[png|jpg] (max 580x380).
{
    "name": "GameScore",
    "description": "GameScore is the GameScore SDK implementation for the Defold game engine.",
    "license": "MIT License",
    "author": "Megalanthus",
    "library_url": "https://github.com/megalanthus/defold-gamescore/archive/master.zip",
    "project_url": "https://github.com/megalanthus/defold-gamescore",
    "forum_url": "",
    "website_url": "",
    "platforms": [
        "html5"
    ],
    "tags": [
        "achievements",
        "ads",
        "analytics",
        "monetization",
        "platform",
        "social"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thank you.

https://github.com/defold/awesome-defold/blob/master/assets/gamescore.json
