### ISSUE TITLE
Plague Lords

### ISSUE THREAD

**Issue by RedUnitStudios** [defold/awesome-defold#91]
```json
{
    "name": "Plague Lords",
	"description": "The investigation of multiple disappearances in the midst of the Black Death turns into a bloody stand against a new mysterious threat. Survive in a turn-based, tactical sandbox, managing a settlement and dozens of peasants, craftsmen and warriors to stop the upcoming Scourge.",
    "url": "https://store.steampowered.com/app/1827240/Plague_Lords/",
    "developer": "Red Unit Studios",
    "publisher": "",
    "releasedate": "Spring 2022",
    "platforms": "Windows,Steam,Switch",
    "images": {
        "full": "https://www.dropbox.com/s/y87aqmjvp9ul8b6/plaguelords-full.jpg",
        "half": "https://www.dropbox.com/s/zty3iw2pz5f6vou/plaguelords-half.jpg",
        "third": "https://www.dropbox.com/s/vw81tc5psbzkizm/plaguelords-third.jpg"
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page

**Comment by RedUnitStudios** [comment]
![plaguelords-full](https://user-images.githubusercontent.com/98483143/151341786-61754d7f-ea4b-4982-931f-d52cc42a6b92.jpg)
![plaguelords-half](https://user-images.githubusercontent.com/98483143/151341794-33214519-72aa-4a67-9f9a-ef918a090b99.jpg)
![plaguelords-third](https://user-images.githubusercontent.com/98483143/151341795-588d81d2-5dd7-4e02-bba8-1496fc576e42.jpg)

**Comment by RedUnitStudios** [comment]
Hey guys! Sry, we've missed that it should be 3000 png to make a correct hover event visualization.
Here it is:

![plaguelords-full](https://user-images.githubusercontent.com/98483143/151365645-6b5e2c7b-81e1-4e11-8512-ff283dd9eb3a.png)

**Comment by britzl** [comment]
Thanks! I'm not sure if you are aware, but it says "Rogurlike", not "Roguelike"

**Comment by RedUnitStudios** [comment]
OMG. Just can't stop rushing. Thanks!
![plaguelords-full](https://user-images.githubusercontent.com/98483143/151545109-9ce4fab6-936d-44b6-ad70-8ee80a1522f8.png)
![plaguelords-half](https://user-images.githubusercontent.com/98483143/151545124-08a91e39-33c5-4e27-bb62-90eead845cb1.png)
![plaguelords-third](https://user-images.githubusercontent.com/98483143/151545132-a1e8131c-ae00-41f0-b019-49c7aec67dbc.png)
!

**Comment by RedUnitStudios** [comment]
Huh.
![plaguelords-full](https://user-images.githubusercontent.com/98483143/151545284-6fd55b63-256d-49e7-b0ec-cda121cb0104.png)
