### ISSUE TITLE
Defold Timer

### ISSUE THREAD

**Issue by klaytonkowalski** [defold/awesome-defold#94]
Optionally also attach two images Defold Timer-hero.[png|jpg] (max 2400x666) and Defold Timer-thumb.[png|jpg] (max 580x380).
{
    "name": "Defold Timer",
    "description": "Defold Timer (dtimer) provides a visual timer widget in a Defold game engine project.",
    "license": "MIT",
    "author": "Klayton Kowalski",
    "library_url": "https://github.com/klaytonkowalski/defold-timer/archive/main.zip",
    "project_url": "https://github.com/klaytonkowalski/defold-timer",
    "forum_url": "https://forum.defold.com/t/defold-timer/70332",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "gui",
        "game mechanic"
    ],
    "images": {
        "hero": "defold-timer.png",
        "thumb": "defold-timer.png"
    }
}

**Comment by britzl** [comment]
Thanks!

https://github.com/defold/awesome-defold/blob/master/assets/defold-timer.json
