### ISSUE TITLE
defold-cognito

### ISSUE THREAD

**Issue by willemt** [defold/awesome-defold#97]
{
    "name": "defold-cognito",
    "description": "Defold native extension which provides access to AWS Cognito. Useful for user signup/login. Supports: iOS, Android.",
    "license": "BSD",
    "author": "willemt",
    "library_url": "",
    "project_url": "https://github.com/willemt/defold-cognito",
    "forum_url": "",
    "website_url": "",
    "platforms": [
        "android",
        "ios"
    ],
    "tags": [],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Added: https://github.com/defold/awesome-defold/blob/master/assets/defold-cognito.json
