### ISSUE TITLE
Craftomation 101

### ISSUE THREAD

**Issue by zulman** [defold/awesome-defold#99]
```json
{
    "name": "Craftomation 101",
	"description": "A craft automation game about funny programmable robots CraftoMates who can move, eat, and craft things needed to terraform a frozen planet",
    "url": "https://luden.io/craftomation/",
    "developer": "Luden.io",
    "publisher": "Nival",
    "releasedate": "TBA",
    "platforms": "iOS,Android,macOS,Windows,Linux,HTML5,Steam,Poki,itch.io",
    "images": {
        "full": "https://user-images.githubusercontent.com/935287/155191029-709539b8-eb18-4562-b3b0-ac88ad5851b7.png",
        "half": "https://user-images.githubusercontent.com/935287/155191058-20947336-6124-4e4b-9117-8e64484dad2e.png",
        "third": "https://user-images.githubusercontent.com/935287/155191070-76a72273-b1d9-4a8f-b0e7-2619f9b97b09.png"
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page

**Comment by britzl** [comment]
Thank you. Added to the showcase page: https://defold.com/showcase/
